### ISSUE TITLE
Coin[0]?

### ISSUE THREAD

**Issue by Jzarecta** [codelardo/CryptocurrenciesScraper#1]
https://github.com/codelardo/CryptocurrenciesScraper/blob/5a03a01c003c5e2636f16b98f95c97ad43223500/src/getCryptocurrenciesData.py#L19

Esta funcion parece que solo crea la primera tabla al poner coin[0] a menos que no lo haya leido bien. Pero el punto es que si se van a generar de una lista, se deberian generar todas, quizas poner un try en caso que ya exista. 

Otra cosa es poner el convertidor de nombres. 
``` coin_table = coin.replace("-", "_") ```

En otro caso se puede tener un diccionario que tenga ambos, y solo hacer referencia a uno.

**Comment by codelardo** [comment]
Se llama a la funcion `db.create_table` con el parametro  `coin[0]` porque `coin` es una tupla en donde la primera posicion esta el nombre de la moneda y en la segunda el link para obtener la data.
